### ISSUE TITLE
feat: allow configuration on deployment resource request and limit

### ISSUE THREAD

**Issue by ChunyiLyu** [syntasso/helm-charts#24]
## Context

Allow configuration on ske-deployment and operator resource request and limit.
We have seen in the wild that the current resource request and limit:
```
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
```

Might be too little for some people's environment. We should make it configurable and consider if these defaults are too little.
