### ISSUE TITLE
strictMatchLabels missing

### ISSUE THREAD

**Issue by tdiaque** [syntasso/helm-charts#3]
Hello,

I am looking to configure destinations with strictMatchLabels: true. However, when inspecting the destinations.yaml templates I am not seeing where we would pass that value or set it to true.

Am I perhaps missing something here?

I am happy to submit a PR.

Your support is greatly appreciated.

**Comment by aclevername** [comment]
Hi @tdiaque 👋 oops it looks like we don't document where the key is, I'll add that to the docs. Its at the top level of the spec, so `.spec.matchLabels` https://github.com/syntasso/kratix/blob/8818e977fff037560fa6e49e92b61a1254146217/api/v1alpha1/destination_types.go#L57

e.g.:
```yaml
apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata: #...
spec:
  strictMatchLabels: true
  destinationSelectors:
    - matchLabels:
      key: value
      
```
