### ISSUE TITLE
bug: ske-operator chart doesn't delete SKE additional resources when set as empty array

### ISSUE THREAD

**Issue by alparslanavci** [syntasso/helm-charts#40]
### Context 

The SKE additional resources are installed by using Helm hooks and they are deleted when the chart is uninstalled. However, if the user wants to delete them by providing an empty array, they are not deleted. 

Steps to reproduce:
1. Install ske-operator chart with SKE additional resources: 
```
skeDeployment:
  enabled: true
  additionalResources:
    - kind: GitStateStore
      apiVersion: platform.kratix.io/v1alpha1
      metadata:
        name: default
      spec:
        secretRef:
          name: git-credentials
          namespace: default
        url: https://172.18.0.2:31333/gitea_admin/kratix
        branch: main
```
2. Verify the additional resources are installed: 
```
$ kubectl get gitstatestores.platform.kratix.io default
NAME      READY
default   False
```
3. Upgrade the chart by setting the SKE additional resources as an empty array:
```
skeDeployment:
  enabled: true
  additionalResources: []
```
4. The additional resources should be deleted, but they are not:
```
$ kubectl get gitstatestores.platform.kratix.io default
NAME      READY
default   False
```
