### ISSUE TITLE
Add filepath mode none to Destination

### ISSUE THREAD

**Issue by tdiaque** [syntasso/helm-charts#5]
Hello,
I do not see spec.filepath.mode in the Destination template, would it be possible to have that added so it can be configured for the destinations?

From the Kratix docs on [Destinations](https://docs.kratix.io/main/reference/destinations/intro)

```
spec:
  # Optional, defaults to `nestedByMetadata`
  # The mode to use when writing to the State Store, valid options are:
  #   - nestedByMetadata: Writes to the State Store in a nested structure
  #   - none: Writes to the State Store in a flat structure
  filepath:
    mode: nestedByMetadata | none
```
